# Generated by Django 3.0.8 on 2020-08-04 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowCasePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='images/')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowCaseGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spectrum_app.ShowCasePhoto')),
            ],
        ),
    ]
