# Generated by Django 3.0.8 on 2020-08-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcasephoto',
            name='slug',
        ),
    ]
