# Generated by Django 3.0.8 on 2020-08-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum_app', '0002_remove_showcasephoto_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showcasegallery',
            old_name='main',
            new_name='couple',
        ),
    ]
