# Generated by Django 3.0.8 on 2020-08-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum_app', '0004_allphoto_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
