# Generated by Django 3.0.8 on 2020-08-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum_app', '0005_sliderphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='allphoto',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
