# Generated by Django 3.0.8 on 2020-08-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum_app', '0006_allphoto_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allphoto',
            name='main_photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
