# Generated by Django 3.0.8 on 2020-08-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum_app', '0007_auto_20200805_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingCouple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('photographer', models.CharField(max_length=50)),
                ('main_photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='WeddingPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spectrum_app.WeddingCouple')),
            ],
        ),
    ]
