# Generated by Django 3.0.8 on 2020-08-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum_app', '0009_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='other_info',
        ),
    ]
