# Generated by Django 3.0.8 on 2020-08-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum_app', '0010_remove_booking_other_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='shoot_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Portrait', 'Portrait'), ('Other events', 'Other events')], max_length=20),
        ),
    ]
