# Generated by Django 3.0.8 on 2020-08-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum_app', '0015_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
