# Generated by Django 3.1.1 on 2020-09-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectrum_app', '0016_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allphoto',
            name='main_photo',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='showcasegallery',
            name='img',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='showcasephoto',
            name='img',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sliderphoto',
            name='img',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='weddingcouple',
            name='main_photo',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='weddingphoto',
            name='img',
            field=models.FileField(upload_to='images/'),
        ),
    ]
